-- ============================================================================
-- Coca-Cola Event Intelligence
-- Reportes persistidos + capa de solo lectura para Power BI.
--
-- 1. report_runs / report_snapshots: cada reporte generado o exportado desde
--    la app deja un registro y una foto de los KPIs de v_event_kpis.
-- 2. public.v_report_*: vistas que lee la app (service_role) para el historial.
-- 3. Esquema powerbi: copias de solo lectura de las vistas v_* sin datos
--    personales, accesibles únicamente por el rol powerbi_reader.
--
-- Solo agrega objetos; no modifica tablas ni vistas existentes.
-- Las vistas públicas existentes usan security_invoker (RLS para usuarios
-- autenticados), por eso Power BI no las lee directamente: las vistas del
-- esquema powerbi se ejecutan con los permisos de su dueño (postgres) y
-- exponen solo columnas agregadas o seudónimas.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tablas
-- ----------------------------------------------------------------------------
CREATE TABLE public.report_runs (
  id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      integer      REFERENCES public.evento (id) ON DELETE SET NULL,
  tipo_reporte  varchar(60)  NOT NULL,
  formato       varchar(4)   NOT NULL,
  parametros    jsonb        NOT NULL DEFAULT '{}'::jsonb,
  generado_por  varchar(120) NOT NULL DEFAULT 'sistema',
  generated_at  timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT chk_report_runs_formato CHECK (formato IN ('csv', 'pdf', 'xlsx')),
  CONSTRAINT chk_report_runs_parametros CHECK (jsonb_typeof(parametros) = 'object')
);

COMMENT ON TABLE public.report_runs IS
  'Cada reporte generado o exportado desde la app (event_id NULL = todos los eventos).';

CREATE INDEX idx_report_runs_generated_at ON public.report_runs (generated_at DESC);
CREATE INDEX idx_report_runs_event        ON public.report_runs (event_id);

CREATE TABLE public.report_snapshots (
  id                bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_run_id     bigint       NOT NULL REFERENCES public.report_runs (id) ON DELETE CASCADE,
  event_id          integer      REFERENCES public.evento (id) ON DELETE SET NULL,
  evento_nombre     varchar(120) NOT NULL,
  registrados       integer      NOT NULL DEFAULT 0,
  asistentes        integer      NOT NULL DEFAULT 0,
  pct_asistencia    numeric,
  interacciones     integer      NOT NULL DEFAULT 0,
  muestras          integer      NOT NULL DEFAULT 0,
  pct_participacion numeric,
  consentimientos   integer      NOT NULL DEFAULT 0,
  conversiones      integer      NOT NULL DEFAULT 0,
  tasa_conversion   numeric,
  canjes            integer      NOT NULL DEFAULT 0,
  satisfaccion      numeric,
  nps               numeric,
  recurrencia       numeric,
  generated_at      timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT uq_report_snapshot_evento UNIQUE (report_run_id, event_id)
);

COMMENT ON TABLE public.report_snapshots IS
  'KPIs congelados de v_event_kpis en el momento de generar cada reporte.';
COMMENT ON COLUMN public.report_snapshots.muestras IS 'Degustaciones (log_activity de tipo degustacion).';
COMMENT ON COLUMN public.report_snapshots.recurrencia IS '% de asistentes con eventos previos.';

CREATE INDEX idx_report_snapshots_event ON public.report_snapshots (event_id);

-- Solo el servidor (service_role) escribe y lee estas tablas.
ALTER TABLE public.report_runs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.report_runs, public.report_snapshots FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.report_runs, public.report_snapshots TO service_role;

-- ----------------------------------------------------------------------------
-- registrar_reporte: guarda el reporte y su snapshot en una sola transacción.
-- ----------------------------------------------------------------------------
CREATE FUNCTION public.registrar_reporte(
  p_event_id     integer,
  p_tipo_reporte text,
  p_formato      text,
  p_parametros   jsonb DEFAULT '{}'::jsonb,
  p_generado_por text  DEFAULT 'sistema'
) RETURNS bigint
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_run_id bigint;
BEGIN
  IF p_event_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM evento WHERE id = p_event_id) THEN
    RAISE EXCEPTION 'El evento % no existe', p_event_id USING ERRCODE = 'P0002';
  END IF;

  INSERT INTO report_runs (event_id, tipo_reporte, formato, parametros, generado_por)
  VALUES (p_event_id, p_tipo_reporte, p_formato, COALESCE(p_parametros, '{}'::jsonb), COALESCE(NULLIF(trim(p_generado_por), ''), 'sistema'))
  RETURNING id INTO v_run_id;

  INSERT INTO report_snapshots (
    report_run_id, event_id, evento_nombre, registrados, asistentes, pct_asistencia,
    interacciones, muestras, pct_participacion, consentimientos, conversiones,
    tasa_conversion, canjes, satisfaccion, nps, recurrencia, generated_at
  )
  SELECT
    v_run_id, k.evento_id, k.evento, k.registrados, k.asistentes, k.pct_asistencia,
    k.interacciones_producto, k.degustaciones, k.pct_participacion,
    k.registros_con_consentimiento, k.conversiones, k.tasa_conversion, k.canjes,
    k.satisfaccion, k.nps, k.pct_recurrencia, now()
  FROM v_event_kpis k
  WHERE p_event_id IS NULL OR k.evento_id = p_event_id;

  IF p_event_id IS NOT NULL AND NOT FOUND THEN
    RAISE EXCEPTION 'El evento % no existe', p_event_id USING ERRCODE = 'P0002';
  END IF;

  RETURN v_run_id;
END;
$$;

COMMENT ON FUNCTION public.registrar_reporte(integer, text, text, jsonb, text) IS
  'Registra un reporte en report_runs y congela los KPIs de v_event_kpis en report_snapshots.';

REVOKE ALL ON FUNCTION public.registrar_reporte(integer, text, text, jsonb, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_reporte(integer, text, text, jsonb, text) TO service_role;

-- ----------------------------------------------------------------------------
-- Vistas de reportes (las lee la app con service_role)
-- ----------------------------------------------------------------------------
CREATE VIEW public.v_report_historial WITH (security_invoker = on) AS
SELECT
  r.id                                  AS report_run_id,
  r.event_id,
  COALESCE(e.nombre, CASE WHEN r.event_id IS NULL THEN 'Todos los eventos' ELSE 'Evento eliminado' END)::varchar(120) AS evento_nombre,
  r.tipo_reporte,
  r.formato,
  r.generado_por,
  r.parametros,
  (SELECT count(*) FROM public.report_snapshots s WHERE s.report_run_id = r.id) AS eventos_incluidos,
  r.generated_at
FROM public.report_runs r
LEFT JOIN public.evento e ON e.id = r.event_id;

COMMENT ON VIEW public.v_report_historial IS 'Historial de reportes generados (fecha, evento, tipo, formato, usuario).';

CREATE VIEW public.v_report_snapshot WITH (security_invoker = on) AS
SELECT
  s.id            AS snapshot_id,
  s.report_run_id,
  s.event_id,
  s.evento_nombre,
  r.tipo_reporte,
  r.formato,
  s.registrados,
  s.asistentes,
  s.pct_asistencia,
  s.interacciones,
  s.muestras,
  s.pct_participacion,
  s.consentimientos,
  s.conversiones,
  s.tasa_conversion,
  s.canjes,
  s.satisfaccion,
  s.nps,
  s.recurrencia,
  s.generated_at
FROM public.report_snapshots s
JOIN public.report_runs r ON r.id = s.report_run_id;

COMMENT ON VIEW public.v_report_snapshot IS 'KPIs congelados por reporte y evento.';

-- Evento A vs Evento B con las cifras vigentes de v_event_kpis.
CREATE VIEW public.v_report_comparacion_eventos WITH (security_invoker = on) AS
SELECT
  a.evento_id                                    AS event_id_a,
  a.evento                                       AS evento_a,
  b.evento_id                                    AS event_id_b,
  b.evento                                       AS evento_b,
  a.asistentes                                   AS asistentes_a,
  b.asistentes                                   AS asistentes_b,
  a.asistentes - b.asistentes                    AS dif_asistentes,
  a.interacciones_producto                       AS interacciones_a,
  b.interacciones_producto                       AS interacciones_b,
  a.interacciones_producto - b.interacciones_producto AS dif_interacciones,
  a.conversiones                                 AS conversiones_a,
  b.conversiones                                 AS conversiones_b,
  a.conversiones - b.conversiones                AS dif_conversiones,
  a.canjes                                       AS canjes_a,
  b.canjes                                       AS canjes_b,
  a.canjes - b.canjes                            AS dif_canjes,
  a.satisfaccion                                 AS satisfaccion_a,
  b.satisfaccion                                 AS satisfaccion_b,
  a.satisfaccion - b.satisfaccion                AS dif_satisfaccion
FROM public.v_event_kpis a
JOIN public.v_event_kpis b ON b.evento_id <> a.evento_id;

COMMENT ON VIEW public.v_report_comparacion_eventos IS
  'Comparación Evento A vs Evento B (todas las parejas): asistentes, interacciones, conversiones, canjes y satisfacción. dif_* = A - B.';

REVOKE ALL ON public.v_report_historial, public.v_report_snapshot, public.v_report_comparacion_eventos FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.v_report_historial, public.v_report_snapshot, public.v_report_comparacion_eventos TO service_role;

-- ============================================================================
-- Esquema powerbi: lo único que ve el rol de Power BI.
-- Sin nombres, apellidos, email, celular, password_hash, códigos QR ni cupones.
--
-- Las vistas públicas v_* usan security_invoker, que comprueba permisos con el
-- usuario conectado aunque se lean desde otra vista. Por eso cada vista se lee
-- mediante una función SECURITY DEFINER (dueño postgres) que devuelve exactamente
-- las mismas filas; así Power BI ve las mismas cifras que la app.
-- ============================================================================
CREATE SCHEMA powerbi;
COMMENT ON SCHEMA powerbi IS 'Vistas de solo lectura para Power BI (rol powerbi_reader).';
REVOKE ALL ON SCHEMA powerbi FROM PUBLIC;

CREATE FUNCTION powerbi.fn_event_kpis() RETURNS SETOF public.v_event_kpis
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_event_kpis $$;
CREATE FUNCTION powerbi.fn_participant_type() RETURNS SETOF public.v_participant_type
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_participant_type $$;
CREATE FUNCTION powerbi.fn_product_interest() RETURNS SETOF public.v_product_interest
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_product_interest $$;
CREATE FUNCTION powerbi.fn_activity_performance() RETURNS SETOF public.v_activity_performance
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_activity_performance $$;
CREATE FUNCTION powerbi.fn_hourly_traffic() RETURNS SETOF public.v_hourly_traffic
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_hourly_traffic $$;
CREATE FUNCTION powerbi.fn_funnel_levels() RETURNS SETOF public.v_funnel_levels
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_funnel_levels $$;
CREATE FUNCTION powerbi.fn_city_map() RETURNS SETOF public.v_city_map
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_city_map $$;
CREATE FUNCTION powerbi.fn_recurrence() RETURNS SETOF public.v_recurrence
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_recurrence $$;
CREATE FUNCTION powerbi.fn_report_historial() RETURNS SETOF public.v_report_historial
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_report_historial $$;
CREATE FUNCTION powerbi.fn_report_snapshot() RETURNS SETOF public.v_report_snapshot
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_report_snapshot $$;
CREATE FUNCTION powerbi.fn_report_comparacion_eventos() RETURNS SETOF public.v_report_comparacion_eventos
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT * FROM public.v_report_comparacion_eventos $$;

-- Dimensión de eventos: tabla central para relacionar por event_id.
-- Las fechas de evento se guardan como hora local de Bolivia (timestamp sin zona).
CREATE VIEW powerbi.v_dim_evento AS
SELECT
  e.id                                         AS event_id,
  e.nombre                                     AS evento,
  te.nombre                                    AS tipo_evento,
  c.nombre                                     AS campana,
  e.ciudad,
  e.lugar,
  e.estado::text                               AS estado,
  e.fecha_inicio AT TIME ZONE 'America/La_Paz' AS fecha_inicio,
  e.fecha_fin    AT TIME ZONE 'America/La_Paz' AS fecha_fin,
  e.participantes_esperados,
  e.presupuesto
FROM public.evento e
JOIN public.tipo_evento te ON te.id = e.tipo_evento_id
LEFT JOIN public.campana c ON c.id = e.campana_id;

-- Mismas columnas y cifras que public.v_event_kpis + conteos para medidas DAX
-- que agregan bien entre varios eventos (NPS y satisfacción ponderados).
CREATE VIEW powerbi.v_event_kpis AS
SELECT
  k.*,
  COALESCE(n.respuestas_nps, 0)          AS respuestas_nps,
  COALESCE(n.promotores, 0)              AS promotores,
  COALESCE(n.detractores, 0)             AS detractores,
  COALESCE(n.respuestas_satisfaccion, 0) AS respuestas_satisfaccion,
  COALESCE(n.suma_satisfaccion, 0)       AS suma_satisfaccion
FROM powerbi.fn_event_kpis() k
LEFT JOIN (
  SELECT
    r.evento_id,
    count(s.nps)                        AS respuestas_nps,
    count(*) FILTER (WHERE s.nps >= 9)  AS promotores,
    count(*) FILTER (WHERE s.nps <= 6)  AS detractores,
    count(s.general)                    AS respuestas_satisfaccion,
    sum(s.general)                      AS suma_satisfaccion
  FROM public.surveys s
  JOIN public.registro_asistido r ON r.id = s.registro_id
  GROUP BY r.evento_id
) n ON n.evento_id = k.evento_id;

-- Audiencia agregada (sin usuario_id, nombre ni apellido). Ciudad y rango de
-- edad solo de personas que dieron consentimiento en algún registro; el resto
-- se agrupa como "Sin consentimiento".
CREATE VIEW powerbi.v_participant_type AS
WITH consentimiento AS (
  SELECT usuario_id, bool_or(consentimiento) AS consentimiento
  FROM public.registro_asistido
  GROUP BY usuario_id
)
SELECT
  p.tipo_participante,
  CASE WHEN c.consentimiento THEN COALESCE(p.rango_edad::text, 'Sin dato') ELSE 'Sin consentimiento' END AS rango_edad,
  CASE WHEN c.consentimiento THEN COALESCE(p.ciudad, 'Sin dato')           ELSE 'Sin consentimiento' END AS ciudad,
  count(*)                   AS personas,
  sum(p.eventos_registrados) AS eventos_registrados,
  sum(p.eventos_asistidos)   AS eventos_asistidos
FROM powerbi.fn_participant_type() p
JOIN consentimiento c ON c.usuario_id = p.usuario_id
GROUP BY 1, 2, 3;

CREATE VIEW powerbi.v_product_interest     AS SELECT * FROM powerbi.fn_product_interest();
CREATE VIEW powerbi.v_activity_performance AS SELECT * FROM powerbi.fn_activity_performance();
CREATE VIEW powerbi.v_hourly_traffic       AS SELECT * FROM powerbi.fn_hourly_traffic();
CREATE VIEW powerbi.v_funnel_levels        AS SELECT * FROM powerbi.fn_funnel_levels();
CREATE VIEW powerbi.v_city_map             AS SELECT * FROM powerbi.fn_city_map();
CREATE VIEW powerbi.v_recurrence           AS SELECT * FROM powerbi.fn_recurrence();

CREATE VIEW powerbi.v_report_historial AS
SELECT report_run_id, event_id, evento_nombre, tipo_reporte, formato, generado_por,
       parametros::text AS parametros, eventos_incluidos, generated_at
FROM powerbi.fn_report_historial();

CREATE VIEW powerbi.v_report_snapshot            AS SELECT * FROM powerbi.fn_report_snapshot();
CREATE VIEW powerbi.v_report_comparacion_eventos AS SELECT * FROM powerbi.fn_report_comparacion_eventos();

-- ----------------------------------------------------------------------------
-- Rol de solo lectura para Power BI. La contraseña NO va en el repositorio:
--   ALTER ROLE powerbi_reader WITH PASSWORD '<contraseña>';   (ver powerbi/README_WINDOWS.md)
-- Sin contraseña el rol no puede iniciar sesión.
-- ----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'powerbi_reader') THEN
    CREATE ROLE powerbi_reader LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 5;
  END IF;
END
$$;

ALTER ROLE powerbi_reader SET default_transaction_read_only = on;
ALTER ROLE powerbi_reader SET statement_timeout = '120s';
ALTER ROLE powerbi_reader SET search_path = powerbi;

-- Las vistas llaman a las funciones con el usuario conectado: necesita EXECUTE,
-- que solo devuelve lo mismo que ya muestran las vistas.
REVOKE ALL ON ALL TABLES    IN SCHEMA powerbi FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA powerbi FROM PUBLIC, anon, authenticated;
GRANT USAGE   ON SCHEMA powerbi TO powerbi_reader;
GRANT SELECT  ON ALL TABLES    IN SCHEMA powerbi TO powerbi_reader;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA powerbi TO powerbi_reader;
